### ISSUE TITLE
Option to regenerate alt text

### ISSUE THREAD

**Issue by beSaif** [adityaoberai/Alt-Text-Generator#12]
A button to regenerate the alt text instead of having to upload the image all over again.

**Comment by adityaoberai** [comment]
The reset button is there so that you can upload a different image, not to keep regenerating text for the same image.

That's a different purpose.

**Comment by adityaoberai** [comment]
Also, I wouldn't expect hitting the Azure Cognitive Services API again and again to return a different caption, so I'm not sure if this option would deem to have merit.
