### ISSUE TITLE
Creation of an api endpoint for users to upload images and generate alt text

### ISSUE THREAD

**Issue by vaishnav-mk** [adityaoberai/Alt-Text-Generator#14]
One additional aspect I'd like to highlight is the absence of rate limits on the internal `/alttext` endpoint. This lack of rate limits can potentially lead to spamming and excessive hits on the azure api

**Comment by adityaoberai** [comment]
That being said, I'd be happy to monitor and consider adding a more substantial rate-limiting solution if usage increases.

**Comment by adityaoberai** [comment]
Since the Vercel function can be used as an API endpoint already, I will improve error handling and create some documentation regarding the same
