### ISSUE TITLE
feat: add a favicon

### ISSUE THREAD

**Issue by priyankarpal** [adityaoberai/Alt-Text-Generator#2]
## What's the feature?
- we need to add a favicon. we are using the vite logo as a favicon.

I want to work on it. 

## Icons suggestions

![Group 1](https://user-images.githubusercontent.com/88102392/235347151-93d24895-7876-4184-a379-820337fdaedf.png)

**Comment by adityaoberai** [comment]
I am currently working on an icon design that can be used as the favicon too.

**Comment by priyankarpal** [comment]
Ok
