### ISSUE TITLE
[FEATURE]: RepoRater badge in README

### ISSUE THREAD

**Issue by eddiejaoude** [adityaoberai/Alt-Text-Generator#27]
Add the following markdown to the `README.md` file for the RepoRater badge 

[![RepoRater](https://repo-rater.eddiehub.io/api/badge?owner=adityaoberai&name=Alt-Text-Generator)](https://repo-rater.eddiehub.io/rate?owner=adityaoberai&name=Alt-Text-Generator)

```markdown
[![RepoRater](https://repo-rater.eddiehub.io/api/badge?owner=adityaoberai&name=Alt-Text-Generator)](https://repo-rater.eddiehub.io/rate?owner=adityaoberai&name=Alt-Text-Generator)
```

**Comment by adityaoberai** [comment]
Additional instruction:

The ideal place to add this badge would be just after Line 5 in the Readme fine (i.e., just after the heading)

**Comment by toukirkhan** [comment]
Can I take up this issue? 😄

**Comment by adityaoberai** [comment]
> Can I take up this issue? 😄

Sure! Go ahead @toukirkhan 👍

**Comment by adityaoberai** [comment]
@toukirkhan make sure to link the issue with the PR and raise a review request from me once the PR is ready 😌

**Comment by toukirkhan** [comment]
@adityaoberai sure thing!! 😄

**Comment by toukirkhan** [comment]
Hey @adityaoberai, I have raised a PR but I am unable to request review on it.

**Comment by AnikethDeb2004** [comment]
can i work on it?
@eddiejaoude @adityaoberai

**Comment by eddiejaoude** [comment]
> can i work on it? eddiejaoude adityaoberai

please read the comments directly above yours, it was requested and assigned to someone else, plus they had already raised a PR that was merged

**Comment by AnikethDeb2004** [comment]
yeah ik better luck next time

**Comment by adityaoberai** [comment]
@AnikethDeb2004 if you find any other issues in the project, feel free to raise them and I'd be happy to work through them with you.

**Comment by AnikethDeb2004** [comment]
Sure @adityaoberai
