### ISSUE TITLE
[Design]: Move GitHub and Contact Links to Header

### ISSUE THREAD

**Issue by i-am-SnehaChauhan** [adityaoberai/Alt-Text-Generator#29]
### Issue Description

The "GitHub" and "Contact" links are currently located in the footer of the website. We need to move them to a header section above the sponsors' images for better visibility and accessibility.

### Proposed Changes

1. Create a new header section above the sponsors' images.
2. Move the "GitHub" and "Contact" links from the footer to this new header section.

**Comment by adityaoberai** [comment]
The **GitHub** and **Sponsor Us** links are left on the bottom intentionally to prioritise focus on the sponsor banner at the top.
