### ISSUE TITLE
chore(dep): migrate to pnpm

### ISSUE THREAD

**Issue by priyankarpal** [adityaoberai/Alt-Text-Generator#3]
## Why to use pnpm?
- `pnpm` is faster than `npm`
- Disk space efficiency
- security etc 

I want to work on it.

**Comment by adityaoberai** [comment]
Not sure if this switch is really necessary, considering the relatively not-so-high scale of the project as well as the use of a limited number of well-tested dependencies.

If you could share more about the potential impact of switching to `pnpm` on this particular app, I'd be happy to consider it.

**Comment by priyankarpal** [comment]
It's faster than nom/yarn that I already mentioned. 

Lots of orgs, projects are using pnpm. Even I'm using for my open source project.

**Comment by adityaoberai** [comment]
> It's faster than nom/yarn that I already mentioned. 
> 
> Lots of orgs, projects are using pnpm. Even I'm using for my open source project. 
> 
> 

Again, fair points. However, what I mean is how substantial would the impact be on this project. Is the effort to replace versus the impact made really worth it in this case?

**Comment by priyankarpal** [comment]
in future we will add more features to this project then to install dependencies we need more time. but in the case of `pnpm` it's not. 

If you're experiencing slow installation times or high disk usage and can't find other solutions, switching to `pnpm` may be a good option. However, if the current workflow is working well and the benefits of switching don't outweigh the costs, it may not be necessary to make the switch.

**Comment by adityaoberai** [comment]
I think, for now, I would let this change be. In case plans change in the future, I'd be happy to revisit this issue and conversation.

Thanks for the suggestion though!

**Comment by priyankarpal** [comment]
> I think, for now, I would let this change be. In case plans change in the future, I'd be happy to revisit this issue and conversation.
> 
> Thanks for the suggestion though!

ok
